services:
  api:
    container_name: virtual-store-api
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - "3001:3000"
    depends_on:
      - db

  db:
    container_name: virtual-store-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: virtual_store
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./database-struture.sql:/docker-entrypoint-initdb.d/0_init.sql
      - my-db:/var/lib/mysql

volumes:
  my-db: